regsvr32 /s mediacom\declrds.ax /u
regsvr32 /s mediacom\Fileinfo.dll /u
regsvr32 /s mediacom\M4.dll /u
regsvr32 /s mediacom\rp.dll /u
regsvr32 /s mediacom\wmedque.dll /u
regsvr32 /s mediacom\WMEncEng.dll /u
regsvr32 /s mediacom\wmesrcwp.dll /u
regsvr32 /s mediacom\wmex.dll /u
regsvr32 /s mediacom\wmprevu.dll /u
regsvr32 /s MPusher.dll /u
